disabled_rules:
    - multiple_closures_with_trailing_closure # for SwiftUI
excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Carthage
    - Pods
identifier_name:
    excluded: # excluded via string array
        - id
        - to
        - or
type_name:
    excluded:
        - ID
